name: progress_indicators
description: A handful collection of some cool progress indicators and text animators.
version: 0.1.4
authors: 
- Asadullah <aubykhan@gmail.com>
- Waleed <waleed_arshad006@hotmail.com>
homepage: https://github.com/wal33d006/progress_indicators

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
