name: progress_indicators
description: A handful collection of some cool progress indicators and text animators.
version: 1.0.0
homepage: https://github.com/wal33d006/progress_indicators

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
